version: '3.8'
services:
  dev-database:
    image: postgres:15.0
    container_name: dev-database
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Abcd1234!
      POSTGRES_DB: testdb
    networks:
      - nestjs-network
networks:
  nestjs-network:
#docker compose up -d

#if you want to start only specified services/container:
#docker compose up -d dev-database -d

#Run a bash shell inside a Container
#docker exec -it dev-database bash

#Go to db
#psql -U postgres -W testdb
